### ISSUE TITLE
Fix and rename to 'unscheduler'

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/scheduler#14]
So this port never had an official release as I ran stuck on the date format issues and couldn't get back to it. Now with [scheduler going into 1.10](https://github.com/backdrop/backdrop-issues/issues/857) this module may be irrelevant except potentially as a renamed "Unscheduler" (as unscheduling functions are not included in core). 

We can probably strip out the scheduling bits, copy from the core issue to get the date/time working for the unscheduling bits, rename the module and get a release.

**Comment by laryn** [comment]
Alternatively, new functionality could  potentially be added to allow scheduling promotion/demotion of content. I had a request for that today but I'm not sure how widespread the need would be, or if it would be worth the effort.

**Comment by stpaultim** [comment]
>  I had a request for that today but I'm not sure how widespread the need would be, or if it would be worth the effort.

That is a feature that sounds very useful to me, but it's not clear I would ever use it. :-)

**Comment by olafgrabienski** [comment]
Providing a way to unschedule content (not possible with core) would fix a regression, so that's the most important thing in my opinion. Re the name, something like Scheduler Extras would cover unscheduling as well as new features.

**Comment by jenlampton** [comment]
@laryn I also think it's reasonable to leave the module the same. Keeping the machine name unchanged would make the upgrade path much simpler for people who are upgrading from Drupal 7. :)

The README should be updated to indicate what the contrib project still does (now that scheduling is in core) so that people who visit this page can decide whether they need unscheduling, and if not, they could choose to remove the module from Backdrop the Backdrop version of their site.

**Comment by laryn** [comment]
Okay, I'm not planning to rename it...
