### ISSUE TITLE
README needs work before publishing a release

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/scheduler#6]

**Comment by Dinornis** [comment]
Hi @laryn, thank you for porting this module.
Here is a rough draft for the README. (not sure what is the best way or format.

**STATUS**
The Scheduler module is currently being ported from Drupal 7 and not ready for release yet.

**DESCRIPTION**
The Scheduler gives content editors the ability to schedule nodes to be published and unpublished at specified dates and times in the future.

Dates can be entered either as plain text or with calendar popups. The Date Popup module is part of the Date module included in Backdrop Core and installed by default.

Scheduler only publishes and unpublishes nodes. If you need to schedule any other activity check out Workflow, Rules, Actions and Job Scheduler.

**NOTES**
Please check that cron is configured to run at the correct interval at /admin/config/system/cron

**INSTALLATION**
1. Visit https://backdropcms.org/user-guide/modules-1 and follow module installation instructions.
2. Grant users the permission "Schedule content publication" so they can set when the nodes they create are to be (un)published.
3. Visit /admin/structure/types and click Configure for any node type and check the box "enable scheduled (un)publishing" for this node type
4. Repeat for all node types that you want scheduled publishing for

The scheduler will run with Backdrop cron, and will (un)publish nodes timed on or before the time at which cron runs.
If you'd like finer granularity to scheduler, but don't want to run Backdrop cron more often (due to its taking too many cycles to run every minute, for example), you can set up another cron job for the scheduler to run independently. Scheduler's cron is at /scheduler/cron; a sample crontab entry to run scheduler every minute would look like:
/usr/bin/wget -O - -q “http://example.com/scheduler/cron"
The path or syntax may differ for your server.

**FEEDS INTEGRATION**
The module provides integration with the Feeds module.

In order to set scheduling dates for publishing or unpublishing imported content you can map the source date fields to the "Scheduler: publish on" and "Scheduler: unpublish on" targets. Make sure the source date fields are using formats that are compatible with the PHP strtotime() function. If needed the date format can be altered by writing a custom FeedsProcessor plugin or by using the Feeds Tamper module.
Feeds module: https://backdropcms.org/project/feeds
PHP strtotime() function: http://php.net/manual/en/function.strtotime.php
The developer's guide to Feeds: https://www.drupal.org/node/622700
Feeds Tamper module: https://www.drupal.org/project/feeds_tamper

**CREDITS**
The Scheduler module has been ported to Backdrop by Laryn Kragt Bakker (https://github.com/laryn).

Scheduler is the work of many people. Some of them are listed here: http://drupal.org/node/3292/committers. But there are even more: All the people who created patches but did not check them in themselves, who posted bug or feature request and those who provided translations and documentation.

This module has been completely rewritten for Drupal 4.7 by:
Ted Serbinski <hello [at] tedserbinski.com> aka "m3avrck" on http://drupal.org

Originally written for Drupal 4.5.0 by:
Moshe Weitzman <weitzman [at] tejasa.com> Gabor Hojtsy <goba [at] php.net> Tom Dobes <tomdobes [at] purdue.edu>

**Comment by laryn** [comment]
Thanks, @Dinornis! I moved some of this into the Wiki area to clean it up a bit.
